config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'recipes/:id/:slug', to: 'recipes#show', as: 'recipe'
  resources :searches, only: %i[index]
  root to: 'searches#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/recipe_import_helper.rb
# frozen_string_literal: true

# Helper methods for importing recipes
module RecipeImportHelper

  def calculate_ttl_cook_time(string)
    return if string.strip.nil? || string.strip.blank?
    arr = extract_time_from(string)
    ttl_mins_from_days  = arr[0] * 1440
    ttl_mins_from_hours = arr[1] * 60
    ttl_mins            = arr[2]

    ttl_mins_from_days + ttl_mins_from_hours + ttl_mins
  end

  def extract_time_from(s)
    s.scan(/(\d{1,2}\s?j)?\s?(\d{1,2}\s?h)?\s?(\d{1,2}\s?)?\s?/)[0].map(&:to_i)
  end

  def find_or_create_recipe(recipe_hash)
    Recipe.find_or_create_by(
      name:        recipe_hash['name'],
      rate:        recipe_hash['rate'],
      author_tip:  recipe_hash['author_tip'],
      budget:      recipe_hash['budget'],
      prep_time:   recipe_hash['prep_time'],
      author:      recipe_hash['author'],
      difficulty:  recipe_hash['difficulty'],
      people_quantity: recipe_hash['people_quantity'],
      cook_time:   recipe_hash['cook_time'],
      total_time:  recipe_hash['total_time'],
      image:       recipe_hash['image'],
      nb_comments: recipe_hash['nb_comments']
    )
  end

  def find_or_create_ingredient(recipe, json_ingredients )
    json_ingredients.each do |ingr|
      ingredient = Ingredient.find_or_create_by(name: ingr, recipe_id: recipe.id)
    end
  end

  def find_or_create_tag(recipe, json_tags )
    json_tags.each do |tag|
      tag = Tag.find_or_create_by(name: tag)
      RecipeTag.find_or_create_by(recipe_id: recipe.id, tag_id: tag.id)
    end
  end


end

app/models/ingredient.rb
# frozen_string_literal: true

# app/models/ingredient.rb
class Ingredient < ApplicationRecord
  # Associations
  belongs_to :recipe

  # Callbacks
  after_create do 
    check_if_optional
    update_recipe_counter
    populate_tsvector
  end

  # Scopes
  scope :get_ingredient_ids_from, -> (array_of_strings) {
    querable_array = array_of_strings.map { |val| "%#{val}%" }
    ingredient_ids = select('ingredients.id')
                      .where('ingredients.name ILIKE ANY (array[?])', querable_array)
  }
  
  private

  def populate_tsvector
    Ingredient.where(id: id).update_all("tsv_name = to_tsvector('english', name)")
  end

  def check_if_optional
    update_attribute(:optional, true) if name.match(/optionnel/)
  end
  
  def update_recipe_counter
    recipe.mandatory_ingredients_count = Ingredient.where(optional: false, recipe_id: recipe.id).count
    recipe.save
  end
end

app/models/recipe.rb
# frozen_string_literal: true

# app/models/recipe.rb
class Recipe < ApplicationRecord
  include RecipeImportHelper
  # Associations
  has_many :ingredients, dependent: :destroy
  has_many :recipe_tags
  has_many :tags, through: :recipe_tags

  # Callbacks
  before_create :import_actions

  # Scopes
  scope :search_by_ingredients, -> (ingredients_array, people, max_time, flexible_search=true) {
    tsvector_clause, ingredients_length = build_tsvector_clause_from(ingredients_array)
    find_by_sql(["
      SELECT r.* FROM recipes r
      INNER JOIN (
        SELECT ingredients.id, ingredients.recipe_id
        FROM ingredients
        WHERE ingredients.id IN (SELECT ingredients.id FROM ingredients
                                 WHERE (#{tsvector_clause}) AND ingredients.optional = false)
      ) q_1 ON r.id = q_1.recipe_id
      WHERE r.people_quantity >= ? AND CAST(r.total_time AS int) <= ?
      GROUP BY r.id
      HAVING COUNT(q_1.id) #{flexible?(flexible_search)}
    ", people || 0, max_time || 90000])
  }


  private

  # Build a flexible search query
  def self.flexible?(flexible)
    return '= r.mandatory_ingredients_count' if flexible == nil
    return '>= 3' if flexible == 'true'
  end

  def self.build_tsvector_clause_from(array)
    ingredients_string_clause =  String.new
    ingredients_length = array.size
    create_ingredients_clause = array.each_with_index do |ingr, i|
      # Get rid of apostrophes
      ingr = ingr.tr(?', ' ')
      # Build the clause
      ingredients_string_clause << "(ingredients.tsv_name @@ websearch_to_tsquery('#{ingr}'))" # or plain_to_tsquery
      ingredients_string_clause << " OR " if i < ingredients_length - 1
    end
    return ingredients_string_clause, ingredients_length
  end

  def import_actions
    self.slug = name.parameterize
    self.total_time = calculate_ttl_cook_time(self.total_time)
  end

end

app/models/recipe_tag.rb
# frozen_string_literal: true

# app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
  self.table_name = 'recipes_tags'
  belongs_to :recipe
  belongs_to :tag
end

app/models/tag.rb
# frozen_string_literal: true

# app/models/tag.rb
class Tag < ApplicationRecord
  has_many :recipe_tags
  has_many :recipes, through: :recipe_tags
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

# app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  # GET /recipes/1
  def show
    recipe = Recipe.find_by(id: params[:id], slug: params[:slug])
    @recipe = RecipeDecorator.new recipe, view_context
  end
end

app/controllers/searches_controller.rb
# frozen_string_literal: true

# app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  rescue_from Pagy::OverflowError, with: :redirect_to_homepage

  def index
    if params[:query].present?
      query, people, max_ttl_time, flexible_search = assign_search_parameters(params)
      @recipes = search_recipes(query, people, max_ttl_time, flexible_search)
                  .map{ |recipe| RecipeDecorator.new(recipe, view_context)}
      @recipes_count = @recipes.size
      @pagy, @recipes = pagy_array(@recipes, items: 10, size: [1, 2, 1, 1])
    else
      @top_recipes = top10_recipes.map{ |recipe| RecipeDecorator.new(recipe, view_context)}
      @pagy, @top_recipes = pagy_array(@top_recipes, items: 5, size: [1, 2, 1, 1])
    end
  end

  private

  # Transfrom query param to an array of string values
  # and also add 'poivre' and 'sel'. Who doesn't have poivre & sel?
  def transform_query_param(query)
    query.split(',').reject(&:blank?).map(&:strip).push('poivre', 'sel')
  end

  def assign_search_parameters(params)
    query = params[:query].strip,
    people = params[:people],
    max_ttl_time = params[:total_time],
    flexible = params[:flexible]
  end


  # Search for Recipes given an array of ingredients
  def search_recipes(query_string, people, max_ttl_time, flexible_search)
    ingredients_array = transform_query_param(query_string)
    Recipe.search_by_ingredients(ingredients_array, people, max_ttl_time, flexible_search)
  end

  # Get TOP10 recipes
  def top10_recipes
    Recipe.where.not(rate: nil).order("rate DESC, nb_comments DESC").first(10)
  end

  def redirect_to_homepage(exception)
    redirect_to(
      url_for(page: exception.pagy.last),
      notice: "Recipes page #{params[:page]} was not found. I have therefore redirected you to homepage."
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  # Inline SVG helper
  def svg(filename, options = {})
    file_path = "#{Rails.root}/app/assets/svgs/icons/#{filename}.svg"
    if File.exist?(file_path)
      file = File.read(file_path).html_safe
      doc  = Nokogiri::HTML::DocumentFragment.parse file
      svg  = doc.at_css 'svg'
      if options[:class].present?
        svg['class'] = options[:class]
      end
      if options[:style].present?
        svg[:style] = options[:style]
      end
      raw doc
    else
      '(not found)'
    end
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recipe_id %>
    <%= form.text_field :recipe_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Recipe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.recipe_id %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipe:</strong>
  <%= @ingredient.recipe_id %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta name="author" content="FridgeJam" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <% if content_for?(:meta) %>
      <%= yield(:meta) %>
    <% else %>
      <title> Welcome | FridgeJam.gr &middot; Fridge powered recipes!</title>
      <meta name="description" content="Fridge powered recipes!">
      <meta name="keywords" content="recipes, tasty dishes, fridge powered recipes">
    <% end %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbo-track': 'reload', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="antialiased">
    <%= render partial: 'partials/header' %>
    <main class="flex flex-col pt-20 pb-6 px-2">
      <%= yield %>
    </main>
    <%= render partial: 'partials/footer' %>
    <% if content_for(:js) %>
      <%= yield(:js) %>
    <% end %>
  </body>
</html>

app/views/partials/_breadcrumb.html.erb
<div class="mb-4">
  <nav class="flex truncate" aria-label="Breadcrumb">
    <ol role="list" class="flex items-center space-x-4">
      <li>
        <div>
          <%= link_to :back, class: 'text-gray-100 hover:text-white' do  %>
            <span class="group inline-flex items-center justify-center p-2 bg-white bg-opacity-20 rounded-full hover:bg-opacity-40  transition ease-in-out duration-300">
              <svg class="-ml-0.5 w-4 h-4 text-orange-100 group-hover:text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path></svg>
            </span>
          <% end %>
        </div>
      </li>
      <li>
        <div class="flex items-center">
          <span class="text-lg font-bold text-white max-w-sm truncate">
            <% if controller_name == 'searches' %>
              Search results for <span class="font-bold">'<%= params[:query]%>'</span>
            <% elsif controller.action_name == 'show' %>
              <%= @recipe.name%> recipe
            <% end %>
          </span>
        </div>
      </li>
    </ol>
  </nav>
</div>

app/views/partials/_footer.html.erb
<footer class="bg-white max-w-2xl mx-auto pb-6">
  <div class="max-w-7xl mx-auto py-0 px-4 overflow-hidden sm:px-6 lg:px-8">
    <div class="mt-8 flex justify-center space-x-6">
      <a href="https://github.com/pskarlas/my_fridge_recipes" target="_blank" class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">GitHub</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
        </svg>
      </a>
    </div>
  </div>
</footer>

app/views/partials/_header.html.erb
<header class="bg-gradient-to-r from-orange-300 to-rose-300 pt-12 md:pt-20 pb-40 px-2">
  <section class="container mx-auto flex flex-col items-center space-y-4">
    <div>
      <a href="/">
      <%= image_tag(
          "fridgejam.png",
          alt: "FridgeJam",
          title: "FridgeJam",
          class: "w-96",
          srcset: { "fridgejam.png" => '2x' } ) %>
        </a>
    </div>
    <div class="w-full max-w-lg">
      <%= form_tag(searches_path, method: :get, id: "searchForm")  do %>
        <label for="query" class="mb-2 text-sm text-white font-medium sr-only">Recipe search</label>

        <div class="relative flex flex-col items-start justify-start space-y-2">
          <%= text_area_tag :query, params[:query], class: 'mb-2 w-full shadow focus:ring-orange-500 focus:border-orange-500 block w-full pl-4 sm:text-sm border-gray-300 rounded-md py-4', :rows => 5, required: true, style: "resize: none;", placeholder: "Write the ingredients comma seperated e.g. orange, porc" %>
          <div class="p-3 rounded-lg bg-orange-500 bg-opacity-20 inline-flex space-x-2 justify-start w-full items-center">
             <%= check_box_tag :flexible, true, true, class: 'focus:ring-sky-500 h-4 w-4 mr-1 text-sky-500 border-orange-300 rounded' %>
             <%= label_tag :flexible,  class: "text-white text-sm cursor-pointer", style: 'text-shadow: 0 0 1px #ffffff;' do %>
               <span class="font-semibold">Flexible search </span>
               <span class="font-light tracking-tight">(recipes with more ingredients are fine)</span>
             <% end %>
          </div>
          <div class="pt-2 w-full flex space-x-4">
            <div class="w-full">
            <%= label_tag :people, 'Min people', class: "inline-block mb-1.5 text-white text-sm font-semibold" %>
            <%= select_tag :people, raw("<option value='0'>I dont' care</option><option value='2'>2 people</option><option value='4'>4 people</option><option value='6'>6 people</option>"), class: 'block w-full py-3 text-base border-gray-300 focus:outline-none shadow focus:ring-orange-500 focus:border-orange-500 sm:text-sm rounded-md' %>
            </div>
            <div class="w-full">
            <%= label_tag :total_time, 'Max recipe time', class: "inline-block mb-1.5 text-white text-sm font-semibold" %>
            <%= select_tag :total_time, raw("<option value='20000'>I don't care</option><option value='30'>30mins</option><option value='60'>60 mins</option><option value='120'>2 hours</option><option value='180'>3 hours</option>"), class: 'block w-full py-3 text-base border-gray-300 focus:outline-none shadow focus:ring-orange-500 focus:border-orange-500 sm:text-sm rounded-md' %>
            </div>
          </div>
        </div>
        <%= button_tag  name: nil, class: "relative inline-flex items-center justify-center mt-4 py-3 w-full rounded px-3 text-lg font-sans font-bold text-white bg-gradient-to-br from-orange-500 to-orange-600 hover:bg-orange-600 hover:cursor-pointer transition ease-in-out duration-300", data: { disable_with: "fetching recipes..." } do  %>
            <div class="absolute right-0 top-0 mr-3 mt-3.5">
              <svg id="spinner" class="hidden animate-spin-fast h-5 w-5 mr-3 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><<path d="M460.115 373.846l-6.941-4.008c-5.546-3.202-7.564-10.177-4.661-15.886 32.971-64.838 31.167-142.731-5.415-205.954-36.504-63.356-103.118-103.876-175.8-107.701C260.952 39.963 256 34.676 256 28.321v-8.012c0-6.904 5.808-12.337 12.703-11.982 83.552 4.306 160.157 50.861 202.106 123.67 42.069 72.703 44.083 162.322 6.034 236.838-3.14 6.149-10.75 8.462-16.728 5.011z"/>
              </svg>
            </div>
            <svg class="-ml-1 mr-2.5 w-5 h-5 fill-current texst-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 416 512">
              <path d="M207.9 15.2c.8 4.7 16.1 94.5 16.1 128.8 0 52.3-27.8 89.6-68.9 104.6L168 486.7c.7 13.7-10.2 25.3-24 25.3H80c-13.7 0-24.7-11.5-24-25.3l12.9-238.1C27.7 233.6 0 196.2 0 144 0 109.6 15.3 19.9 16.1 15.2 19.3-5.1 61.4-5.4 64 16.3v141.2c1.3 3.4 15.1 3.2 16 0 1.4-25.3 7.9-139.2 8-141.8 3.3-20.8 44.7-20.8 47.9 0 .2 2.7 6.6 116.5 8 141.8.9 3.2 14.8 3.4 16 0V16.3c2.6-21.6 44.8-21.4 48-1.1zm119.2 285.7l-15 185.1c-1.2 14 9.9 26 23.9 26h56c13.3 0 24-10.7 24-24V24c0-13.2-10.7-24-24-24-82.5 0-221.4 178.5-64.9 300.9z"/>
            </svg>
            search
        <% end %>
      <% end%>
    </div>
  </section>
</header>

app/views/partials/_notification.erb
<p class="notice text-white mb-4 text-lg"><%= notice %></p>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/partials/_filters_modal.html.erb
<div data-modal-target="modal"
    data-transition-enter="transition ease-out duration-100"
    data-transition-enter-start="opacity-0 translate-y-1"
    data-transition-enter-end="opacity-100 translate-y-0"
    data-transition-leave="transition ease-in duration-150"
    data-transition-leave-start="opacity-100 translate-y-0"
    data-transition-leave-end="opacity-0 translate-y-1"
    class="hidden fixed z-10 inset-0 overflow-y-auto">
  <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
    <div class="fixed inset-0 transition-opacity" aria-hidden="true" data-action="click->modal#closeModal">
      <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
    </div>
    <%# This element is to trick the browser into centering the modal contents. %>
    <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
    <div class="inline-block align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-md sm:w-full sm:p-6" role="dialog" aria-modal="true" aria-labelledby="modal-headline">
      <div class="block absolute top-0 right-0 pt-4 pr-4">
        <button data-action="click->modal#closeModal" type="button" class="bg-white rounded-md text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500">
          <span class="sr-only">Close</span>
          <!-- Heroicon name: outline/x -->
          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div>
        <div class="mx-auto flex items-center justify-center h-20 w-20 rounded-full bg-green-100">
          <svg class="h-8 w-8 text-green-700" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z"></path></svg>
        </div>
        <div class="mt-3 text-left sm:mt-5">
          <div class="text-center">
            <h3 class="text-2xl md:text-2xl font-medium leading-7 text-gray-800 tracking-tight">
              filters content
            </h3>
            <div class="mt-2.5 mx-auto w-full flex justify-center">
              <p class="text-gray-500 text-base max-w-sm mx-auto">
                Description
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recipes/partials/_recipe.html.erb
<li class="py-4">
  <%= link_to recipe_path(recipe.id, recipe.slug), class: " flex items-center space-x-4" do %>
    <div class="flex-shrink-0 bg-gray-50">
      <img class="object-center object-cover  h-24 w-32 rounded-md" src="<%= recipe.image_url %>" alt="<%= recipe.name %>" title="<%= recipe.name %>">
    </div>
    <div class="flex-1 min-w-0  space-y-1">
      <%= recipe.dificulty_badge %>
      <div class="">
        <p class="text-lg font-medium text-gray-900 truncate">
          <%= recipe.name %>
        </p>
        <div class="flex items-center space-x-1 text-sm text-gray-500 truncate">
          <span class="flex items-center">
            <%= svg 'clock', class: 'w-3.5 h-3.5 mr-1' %>
            <span class="font-semibold">
              <%= distance_of_time_in_words(0, recipe.total_time.minutes) %>
            </span>
          </span>
          <span>&middot;</span>
          <span>
            <span class="font-semibold">
              <%= pluralize recipe.people_quantity, 'person', 'persons' %>
            </span>
          </span>
        </div>
      </div>
    </div>
    <div>
      <span class="inline-flex items-center shadow-sm px-2.5 py-0.5 border border-gray-300 text-sm leading-5 font-medium rounded-full text-gray-700 bg-white hover:bg-gray-50">
        View
      </span>
    </div>
  <% end %>
</li>

app/views/recipes/partials/_top10.html.erb
<h2 class="text-2xl font-bold text-gray-900">
  TOP 10 Recipes
</h2>
<div class="flow-root mt-10">
  <ul role="list" class="-my-5 divide-y divide-gray-200">
    <% @top_recipes.each do |recipe|%>
      <%= render partial: 'recipes/partials/recipe', locals: {recipe: recipe} %>
    <% end %>
  </ul>
  <div class="mt-10 pt-6 flex border-t border-gray-100 items-center justify-center p-2">
    <%= pagy_nav(@pagy).html_safe if @pagy.pages > 1 %>
  </div>
</div>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>